url: ""
baseurl: ""

# Site settings
title: Li-Kang Weng 翁立剛
email: eqttonytony@gmail.com
description: "It's the website about Li-Kang (Tony) Weng from Taiwan!"
# "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Li-Kang (Tony) Weng 翁立剛
  pic: 1
  position: #
  social:
    - title: github
      url: https://github.com/escrowdis
    - title: mail
      url: mailto:eqttonytony@gmail.com
    - title: linkedin
      url: https://www.linkedin.com/in/lkw-tw/

# Build settings
markdown: kramdown
permalink: pretty
